Add bookings
StRaiGT/java-shareit pull request #2
Opened 2023-01-30 20:54 UTC by StRaiGT

2023-02-01 12:44 UTC, AnastasiyaFomkina requested changes
Отличная работа - молодец 👍  Оставила немного комментариев, как проект можно причесать. Из общего: 
Нужно максимально разнести классы по пакетам, например, создать для комментариев отдельный подпакет в пакете `item`, сервисы вынести в подпакет `service`, модели в пакет `domain` или `model` и так далее

2023-02-01 12:44 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +        return getClass().hashCode();
Лучше считать хэш по определенным полям класса, так будет более точно определяться значение. Можно переопределить с помощью горячих клавиш идеи: [Alt+Insert](https://www.jetbrains.com/idea/guide/tips/generate-code/#:~:text=You%20can%20generate%20new%20code,Insert%20(Windows%2FLinux).)
Нужно поправить во всех классах, где переопределяются `equals и hashCode`

2023-02-01 12:44 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private final String headerUserId = "X-Sharer-User-Id";
Лучше сделать константным значением: `static final`. Поправь, пожалуйста, по всему проекту

2023-02-01 12:44 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public final BookingService bookingService;
Лучше максимально скрывать область видимости полей класса, если они используются только внутри определенного класса

2023-02-01 12:44 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +        return itemMapper.mapUserFromUserId(userId);
_Опционально_
В маппере лучше не использовать методы других классов, лучше передавать определенный параметр и проставлять его в нужное поле сущности. А вот логику получения этого параметра уже лучше реализовывать в сервисе, так как она может расширяться. 
Если решишь исправлять, то нужно поправить все мапперы

2023-02-01 12:44 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/BookingRequestDto.java
> +    @Future
Может быть `@FutureOrPresent`

2023-02-01 19:07 UTC, StRaiGT commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +        return getClass().hashCode();
Поправил

2023-02-01 19:07 UTC, StRaiGT commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public final BookingService bookingService;
Проглядел... Исправил.

2023-02-01 19:16 UTC, StRaiGT commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private final String headerUserId = "X-Sharer-User-Id";
Сделал

2023-02-01 19:22 UTC, StRaiGT commented on src/main/java/ru/practicum/shareit/booking/BookingRequestDto.java
> +    @Future
Согласен

2023-02-01 22:10 UTC, StRaiGT commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +        return itemMapper.mapUserFromUserId(userId);
Поправил все мапперы

2023-02-01 22:11 UTC, StRaiGT commented
Разнес все по пакетам

2023-02-02 08:49 UTC, AnastasiyaFomkina approved these changes

2023-02-02 09:15 UTC, merged