Add item requests
StRaiGT/java-shareit pull request #3
Opened 2023-02-10 10:42 UTC by StRaiGT

2023-02-15 08:20 UTC, AnastasiyaFomkina requested changes
Спасибо, что написал такие подробные тесты - ты проделал огромную работу, молодец 🔥
Оставила к тестам несколько небольших комментариев, не стала их дублировать для каждого из тестов, нужно будет отследить такое же поведение в других тестах и тоже поправить

2023-02-15 08:20 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +            @RequestParam(defaultValue = UserController.PAGE_DEFAULT_SIZE, required = false) @Positive Integer size) {
Можно сразу ожидать от клиента `Pageable pageable`, так не придется настраивать основные поля для пагинации и добавлять новые, если потребуется

2023-02-15 08:20 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +public abstract class ItemMapper {
Можно оставить интерфейсом

2023-02-15 08:20 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +    protected List<CommentDto> commentsToCommentsDto(List<Comment> comments) {
Тогда этот метод нужно будет обозначить, как [default](https://sysout.ru/defaut-method-v-java/)

2023-02-15 08:20 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Page<Booking> bookings = null;
Даже с пагинацией мы можем получить список, просто в этом списке будет заранее определенно количество элементов. Лучше вернуть, как было, так как мы не используем и нам не нужны возможности Page, а со списком работать гораздо удобнее

2023-02-15 08:20 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
>          switch (state) {
_Задание со "*"_
Данный блок кода можно оптимизировать с помощью паттерна проектирования 
[Цепочка обязанностей](https://refactoring.guru/ru/design-patterns/chain-of-responsibility) (сайт может не открываться без vpn).
Предлагаю изучить этот паттерн и попробовать реализовать его.

В коммерческой разработке очень часто используются паттерны проектирования, так как код становится более чистым и структурированным. А еще его становится проще поддерживать и масштабировать. 

А еще их часто спрашивают на собеседованиях 😉

2023-02-15 08:20 UTC, afomkina commented on src/test/java/ru/practicum/shareit/booking/BookingMapperImplTest.java
> +    public static void beforeAll() {
_Опционально_
В тестах лучше отказаться от статических `@BeforeAll` и `@AfterAll`, лучше использовать `@BeforeEach` и `@AfterEach`, чтобы контекст тестов всегда был чистым и ничего не перетиралось.

Все используемые параметры лучше сразу инициализировать при создании, если нам не нужно обновлять/пересоздавать их перед каждым из тестов

2023-02-15 08:20 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +            assertEquals(0, result.size());
```suggestion
            assertTrue(result.isEmpty());
```
Поправь, пожалуйста, во всех случаях, где проверяется, что список пуст

2023-02-15 08:20 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +            assertEquals(booking.getId(), result.get(0).getId());
`result.get(0)` можно вынести в переменную

2023-02-15 08:20 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +            assertEquals(booking.getItem().getOwner().getId(), result.get(0).getItem().getOwnerId());
Проверки со строк 238-250 повторяются ниже в других тестах, нужно их вынести в отдельный метод и использовать его, а не дублировать код

2023-02-15 09:59 UTC, StRaiGT commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +            @RequestParam(defaultValue = UserController.PAGE_DEFAULT_SIZE, required = false) @Positive Integer size) {
Да, можно добавить Pageable pageable (и варианты с @PageableDefault).
Однако тесты постмана не будут проходить, т.к. при запросе с некоректными значениями будут использоваться дефолтные значения (0,20)

2023-02-15 10:04 UTC, StRaiGT commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +public abstract class ItemMapper {
done

2023-02-15 10:04 UTC, StRaiGT commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +    protected List<CommentDto> commentsToCommentsDto(List<Comment> comments) {
🔥

2023-02-15 10:34 UTC, StRaiGT commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Page<Booking> bookings = null;
поправил везде

2023-02-15 12:34 UTC, StRaiGT commented on src/test/java/ru/practicum/shareit/booking/BookingMapperImplTest.java
> +    public static void beforeAll() {
Переделал

2023-02-15 12:34 UTC, StRaiGT commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +            assertEquals(0, result.size());
Переделал

2023-02-15 13:28 UTC, StRaiGT commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +            assertEquals(booking.getId(), result.get(0).getId());
done

2023-02-15 14:54 UTC, StRaiGT commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +            assertEquals(booking.getItem().getOwner().getId(), result.get(0).getItem().getOwnerId());
Минус 120 строк повторяющегося кода в этом классе 🔥
Поправил везде.

2023-02-15 21:21 UTC, StRaiGT commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
>          switch (state) {
Разобрался и применил

2023-02-16 13:12 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +            @RequestParam(defaultValue = UserController.PAGE_DEFAULT_SIZE, required = false) @Positive Integer size) {
Эх, жаль, что тесты проходить не будут :(

2023-02-16 17:02 UTC, AnastasiyaFomkina requested changes

2023-02-16 17:02 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/chainSearcher/booker/ChainSearcherByBooker.java
> +public class ChainSearcherByBooker {
Молодец, что разобрался и реализовал цепочку обязанностей - это очень круто 👍

2023-02-16 17:02 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/chainSearcher/Searcher.java
> +public abstract class Searcher {
Можно еще больше оптимизировать данный класс, чтобы совсем убрать повторения. 
Для начала нужно вынести метод `findAll` в класс `Searcher`, чтобы оптимизировать этот метод под все классы наследники, нужно выделить два абстрактных метода:
- первый заменит нам проверку на `state`: он должен возвращать `boolean`. Им мы заменим условие внутри блока if
- второй должен возвращать список бронирований и принимать в качестве параметров все нужные аргументы

Тогда во всех классах-наследниках останется только переопределить логку поиска нужного стейта и логику получения списка бронирваний.

Вот патч с примером, можно немножко подглядеть:
[Optimize_chain_of_responsibility.patch](https://github.com/StRaiGT/java-shareit/files/10758499/Optimize_chain_of_responsibility.patch)

2023-02-16 19:17 UTC, StRaiGT commented on src/main/java/ru/practicum/shareit/booking/chainSearcher/Searcher.java
> +public abstract class Searcher {
Хорошая идея!

2023-02-17 15:19 UTC, AnastasiyaFomkina approved these changes
🔥

2023-02-17 15:31 UTC, merged