Add docker
StRaiGT/java-shareit pull request #4
Opened 2023-02-24 16:56 UTC by StRaiGT

2023-02-25 21:30 UTC, andrew-larkin requested changes
Привет! Отлично, очень сильная работа, код промышленного уровня. Архитектура, реализация бизнес-логики и тестов выполнены очень качественно. Пара правок и можно будет приступать к диплому.

2023-02-25 21:30 UTC, andrew-larkin commented on docker-compose.yml
> +    image: postgres:15.1-alpine
для бд еще хорошо бы добавить настройку для volumes

2023-02-25 21:30 UTC, andrew-larkin commented on docker-compose.yml
> +    ports:
здесь еще не помешает настройка restart on failure - чтобы если наш сервер упадет и начнет заново запускаться, gateway не завалился вслед за ним

2023-02-25 21:30 UTC, andrew-larkin commented on gateway/src/main/java/ru/practicum/shareit/booking/model/BookingRequestDto.java
>  @FieldDefaults(level = AccessLevel.PRIVATE)
классная аннотация!

2023-02-25 21:30 UTC, andrew-larkin commented on gateway/src/main/resources/application.properties
> +#logging.level.org.apache.http=DEBUG
закомментированный код и настройки следует удалить

2023-02-25 21:30 UTC, andrew-larkin commented on gateway/src/test/java/ru/practicum/shareit/controller/BookingControllerTest.java
> +    private final UserDto userDto1 = UserDto.builder()
в реальных проектах для наполнения БД обычно используются sql-скрипты. Очень удобно, занимают мало места и можно использовать в одном тестовом классе для разных ситуаций. Это чисто информативное сообщение, я не предлагаю переписывать что-либо. Сами тесты сделано здорово, отлично!

2023-02-26 07:35 UTC, StRaiGT commented on gateway/src/main/resources/application.properties
> +#logging.level.org.apache.http=DEBUG
удалил закомментированные отладочные настройки

2023-02-26 08:02 UTC, StRaiGT commented on docker-compose.yml
> +    ports:
добавил

2023-02-26 08:34 UTC, StRaiGT commented on docker-compose.yml
> +    image: postgres:15.1-alpine
добавил создание именованного тома и хранение данных в нём

2023-02-26 12:40 UTC, merged